test3

diff --git a/.github/workflows/status_check.yml b/.github/workflows/status_check.yml
--- a/.github/workflows/status_check.yml
+++ b/.github/workflows/status_check.yml
@@ -9,19 +9,27 @@
 #|                                                                           |
 #-----------------------------------------------------------------------------
 name: Status Check
-on:
-  pull_request:
-    paths:
-      - '.github/**'
 
+on: [pull_request]
 jobs:
   YAMLCheck:
-    name: Yaml Modification Check
     runs-on: ubuntu-latest
-    steps:
-      - name: Checkout Repository
-        uses: actions/checkout@v3
 
-      - name: Check for YAML File Changes       
-        run: |
-          echo "::error::The ./github/workflows file was changed by ${GITHUB_ACTOR}. Aborting workflow because of the possibility of malicious intent."
+    steps:
+    - name: Checkout Code
+      uses: actions/checkout@v2
+      with:
+        ref: ${{ github.event.pull_request.head.ref }}
+        fetch-depth: 0
+
+    - name: Compare .github Folders
+      id: compare
+      run: |
+        diff=$(git diff --name-only HEAD^ HEAD .github)
+        if [ -n "$diff" ]; then
+          echo "::error::The ./github/** directory was changed by ${GITHUB_ACTOR}. Aborting workflow because of the possibility of malicious intent."
+          exit 1
+        else
+          echo "No Files Were Modified in ./github/** Safe to Proceed With Runners"
+          exit 0
+        fi
