changes

diff --git a/.github/workflows/status_checks.yml b/.github/workflows/status_checks.yml
--- a/.github/workflows/status_checks.yml
+++ b/.github/workflows/status_checks.yml
@@ -9,20 +9,20 @@
 #|                                                                           |
 #-----------------------------------------------------------------------------
 name: Status Check
-on: push
+on: 
+  push:
+    paths:
+      -'.github/workflows'
 jobs:
   YAMLCheck:
     name: Yaml Modification Check
     runs-on: ubuntu-latest
     steps:
       - name: Check if workflows file was changed
-        uses: actions/github-script@v3
-        with:
-          script: |
-            const filesChanged = context.payload.commits[0].added.concat(context.payload.commits[0].modified);
-            core.setOutput('filesChanged', filesChanged.includes('.github/workflows'));
-      - name: Fail if YAML was modified
-        if: ${{ steps.check-file.outputs.filesChanged == 'true' }}
+        uses: actions/checkout@v2
         run: |
-          echo "::error::The ./github/workflows file was changed by ${GITHUB_ACTOR}. Aborting workflow because of the possibility of malicious intent."
-          exit 1
+          if git diff --quiet HEAD@{1} HEAD .github/workflows; then
+          else
+            echo "::error::The ./github/workflows file was changed by ${GITHUB_ACTOR}. Aborting workflow because of the possibility of malicious intent."
+            exit 1
+          fi
